In [1]:
# imports
import jax
import jax.numpy as jnp
import numpy as np
# Node and Network
from Node import Node
from Network import Cluster

In [2]:
# Test of node class
Node0 = Node(0.1, jnp.array([0.5]), jnp.array([0.5]), 0)

In [3]:
# Create a few more nodes for testing
Node0 = Node(0, jnp.array([]), jnp.array([]), 0)
Node1 = Node(0, jnp.array([]), jnp.array([]), 1)
Node2 = Node(0, jnp.array([]), jnp.array([]), 2)
Node3 = Node(0, jnp.array([]), jnp.array([]), 3)
Node4 = Node(0, jnp.array([]), jnp.array([]), 4)
Node5 = Node(0, jnp.array([]), jnp.array([]), 5)
nodes = [Node0, Node1, Node2, Node3, Node4, Node5]

In [4]:
Cluster1 = Cluster(1, 1, nodes=nodes, init_net=False)


In [5]:
Cluster1.add_connection(Node0, Node1)
Cluster1.add_connection(Node1, Node2)
Cluster1.add_connection(Node0, Node3)
Cluster1.add_connection(Node1, Node0)
Cluster1.add_connection(Node2, Node5)

In [6]:
Cluster1.print_connections()

[[0. 1. 0. 1. 0. 0.]
 [1. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [7]:
Cluster1.get_neighbors(Node0, 2)

Array([2], dtype=int32)

In [53]:
input = jnp.array([1])
print(Cluster1.run(input))
Cluster1.print_activations()

[0.01666667]
Node:  0 Activation:  1.0666666
Node:  1 Activation:  0.26666665
Node:  2 Activation:  0.06666666
Node:  3 Activation:  0.26666665
Node:  4 Activation:  0.0
Node:  5 Activation:  0.016666666
